#!/bin/sh
# Generate post-quantum fixtures and run every available probe against them.
#
# Each probe is a small, self-contained program that exercises one default
# path in one runtime. A probe exits 0 when the path survived the certificate
# and non-zero when it did not — so a FAIL here is the demo working, not the
# demo broken.
#
# Runtimes that are not installed are skipped, loudly, rather than silently
# reducing the result table.
#
# Usage: docs/demo/run.sh [output-dir]

set -eu

demo_dir="$(cd "$(dirname "$0")" && pwd)"
repo_root="$(cd "${demo_dir}/../.." && pwd)"
work_dir="${1:-${repo_root}/dist/demo}"

# Prefer a locally built binary so the demo tracks the working tree; fall back
# to whatever is on PATH for readers who installed a release.
if [ -x "${repo_root}/bin/pqc-fixtures" ]; then
  pqc="${repo_root}/bin/pqc-fixtures"
elif command -v pqc-fixtures >/dev/null 2>&1; then
  pqc="$(command -v pqc-fixtures)"
else
  echo "pqc-fixtures not found: run 'make build' or install a release" >&2
  exit 1
fi

# The bundled engine lives beside a release binary. For a working-tree build it
# has to be pointed at explicitly.
if [ -z "${PQC_FIXTURES_OPENSSL:-}" ] && [ -x "${repo_root}/dist/engine/openssl" ]; then
  PQC_FIXTURES_OPENSSL="${repo_root}/dist/engine/openssl"
  export PQC_FIXTURES_OPENSSL
fi

pass=0
fail=0
skip=0

section() {
  printf '\n\033[1m%s\033[0m\n' "$1"
}

# probe <label> <command...> — run a probe, keep its exit status, and tally it.
# `set -e` is off for the probe itself: a probe that reports a broken default
# by exiting non-zero is a result, not a script failure.
probe() {
  label="$1"
  shift
  status=0
  "$@" || status=$?
  if [ "${status}" -eq 0 ]; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
  fi
}

# psql exits 0 under ON_ERROR_STOP=0 even when every statement was rejected,
# so its exit status cannot be the verdict. The server's own ERROR lines can.
run_postgres_probe() {
  pg_output="$(psql -X -q -v ON_ERROR_STOP=0 \
    -v chain="${work_dir}/ml-dsa-65/INSECURE-TEST-fullchain.pem" \
    -f "${demo_dir}/probes/postgres-cert-column.sql" 2>&1)"
  printf '%s\n' "${pg_output}"
  if printf '%s' "${pg_output}" | grep -q 'ERROR:'; then
    rejected="$(printf '%s' "${pg_output}" | grep -c 'ERROR:')"
    printf '  RESULT              FAIL — PostgreSQL rejected %s statement(s)\n' "${rejected}"
    return 1
  fi
  printf '  RESULT              PASS — every statement was accepted\n'
  return 0
}

skipped() {
  printf '  SKIPPED             %s\n' "$1"
  skip=$((skip + 1))
}

echo "pqc-fixtures demo — do default paths survive post-quantum certificate sizes?"
echo "binary: ${pqc}"
"${pqc}" --version

rm -rf "${work_dir}"
mkdir -p "${work_dir}"

section "Generating fixtures"
# ml-dsa-65 is the mainstream choice; worst-case-tls is the pathological one.
"${pqc}" gen --algo ml-dsa-65 --chain 3 --out "${work_dir}/ml-dsa-65" --quiet
"${pqc}" gen --preset worst-case-tls --out "${work_dir}/worst-case-tls" --quiet
# deep-chain exists to sit on Java's certificate-count limit rather than its
# byte limit, so the Java probe needs it even though the Node probes do not.
"${pqc}" gen --preset deep-chain --out "${work_dir}/deep-chain" --quiet
for set in ml-dsa-65 worst-case-tls deep-chain; do
  printf '  %-14s %s B of PEM chain\n' "${set}" \
    "$(wc -c < "${work_dir}/${set}/INSECURE-TEST-fullchain.pem" | tr -d ' ')"
done

# A classical certificate, generated by the same engine, so the comparison is
# like-for-like: same tool, same day, only the algorithm differs.
OPENSSL_CONF=/dev/null "${PQC_FIXTURES_OPENSSL:-openssl}" req -x509 -newkey rsa:2048 -nodes \
  -keyout "${work_dir}/rsa-2048.key" -out "${work_dir}/rsa-2048.crt" \
  -days 30 -subj "/CN=TEST ONLY baseline" >/dev/null 2>&1
echo "  rsa-2048       $(wc -c < "${work_dir}/rsa-2048.crt" | tr -d ' ') B baseline certificate"

if command -v node >/dev/null 2>&1; then
  section "Node — certificate forwarded in a request header (mTLS behind a proxy)"
  for case_spec in \
    "rsa-2048.crt|RSA-2048 leaf (baseline)" \
    "ml-dsa-65/INSECURE-TEST-leaf.cert.pem|ML-DSA-65 leaf" \
    "ml-dsa-65/INSECURE-TEST-fullchain.pem|ML-DSA-65 chain" \
    "worst-case-tls/INSECURE-TEST-leaf.cert.pem|SLH-DSA-SHA2-256f leaf"; do
    path="${case_spec%%|*}"
    label="${case_spec#*|}"
    printf '\n  %s\n' "${label}"
    probe "${label}" node "${demo_dir}/probes/node-cert-header.mjs" "${work_dir}/${path}" "${label}"
  done

  section "Node — terminating TLS with the certificate"
  for case_spec in "ml-dsa-65|ML-DSA-65" "worst-case-tls|SLH-DSA-SHA2-256f"; do
    dir="${case_spec%%|*}"
    label="${case_spec#*|}"
    printf '\n  %s\n' "${label}"
    probe "${label}" node "${demo_dir}/probes/node-tls-handshake.mjs" "${work_dir}/${dir}" "${label}"
  done
else
  section "Node"
  skipped "node is not installed"
fi

if java -version >/dev/null 2>&1; then
  section "Java — TLS handshake message size limits"
  probe "java" java "${demo_dir}/probes/JavaHandshakeLimits.java" "${work_dir}"
else
  section "Java"
  skipped "no working java runtime (JDK 24+ needed for ML-DSA)"
fi

if ! command -v psql >/dev/null 2>&1; then
  section "PostgreSQL"
  skipped "psql is not installed"
elif ! pg_error="$(psql -X -q -t -c 'SELECT 1' 2>&1 >/dev/null)"; then
  # Report why, rather than "not reachable". A skip that hides its own cause
  # is how a red result table quietly turns green.
  section "PostgreSQL"
  skipped "psql cannot connect: $(printf '%s' "${pg_error}" | tr '\n' ' ')"
else
  section "PostgreSQL — storing the certificate in a column"
  probe "postgres" run_postgres_probe
fi

section "Summary"
printf '  %d survived, %d broke, %d skipped\n' "${pass}" "${fail}" "${skip}"
printf '  fixtures left in %s\n' "${work_dir}"
echo
echo "  A 'broke' line is a default in your stack that a post-quantum"
echo "  certificate will hit. None of these are bugs in the certificate."
